export const SET_BOARD_NAME = 'SET_BOARD_NAME';
export const SET_COLLECTIONS = 'SET_COLLECTIONS';

export const ADD_TASK_ID_TO_COLLECTION = 'ADD_TASK';
export const REMOVE_TASK_ID_FROM_COLLECTION = 'REMOVE_TASK_ID_FROM_COLLECTION';
export const REORDER_TASK_IDS_IN_COLLECTION = 'REORDER_TASK_IDS_IN_COLLECTION';
export const ADD_COLLECTION = 'ADD_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';

export const MOVE_TASK = 'MOVE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const REORDER_TASK = 'REORDER_TASK';
